<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-37VOAJ4" failures="0" tests="4" name="com.nghiapd.mathutil.core.MathutilTest" time="0.004" errors="0" timestamp="14 thg 10 2022 03:12:25 GMT">
  <testcase classname="com.nghiapd.mathutil.core.MathutilTest" name="tryAssert on tryAssert(com.nghiapd.mathutil.core.MathutilTest)" time="0.001"/>
  <testcase classname="com.nghiapd.mathutil.core.MathutilTest" name="testFactorialGivenWrongArgumentThrowsException on testFactorialGivenWrongArgumentThrowsException(com.nghiapd.mathutil.core.MathutilTest)" time="0.001"/>
  <testcase classname="com.nghiapd.mathutil.core.MathutilTest" name="testFactorialGivenRightArgumentReturnsWell2 on testFactorialGivenRightArgumentReturnsWell2(com.nghiapd.mathutil.core.MathutilTest)" time="0.001"/>
  <testcase classname="com.nghiapd.mathutil.core.MathutilTest" name="testFactorialGivenRightArgumentReturnsWell on testFactorialGivenRightArgumentReturnsWell(com.nghiapd.mathutil.core.MathutilTest)" time="0.002"/>
</testsuite> <!-- com.nghiapd.mathutil.core.MathutilTest -->
